### ISSUE TITLE
getting a 'Normal is not a module (TypeError)' 

### ISSUE THREAD

**Issue by dfuentes77** [zombocom/derailed_benchmarks#200]
when trying to run `bundle exec derailed bundle:mem`

```
/distribution-0.7.3/lib/distribution/normal/ruby.rb:2:in `<module:Distribution>': Normal is not a module (TypeError)
```

block at top of said file:
```
module Distribution
  module Normal
    module Ruby_
      class << self
```

What do I need to do to get passed this point since this gem works just fine for us.

**Comment by dfuentes77** [comment]
I've added `require: false` in the meantime to get passed this.  And I've opened https://github.com/clbustos/distribution/issues/31

**Comment by schneems** [comment]
You've got one thing defining `Normal` as a class and another as a module. You'll need to see what is setting it. 

You can use https://www.schneems.com/2016/01/25/ruby-debugging-magic-cheat-sheet.html. 

```
sup(Distribution::Normal)
```

At the top of your file and it might point to where it's defined. Or try `Distribution.const_source_location(:Normal)`.

This doesn't look like a bug in derailed, it looks like an issue with your app or another library. Derailed doesn't set that constant.
