### ISSUE TITLE
I don't get this result, seems out of whack

### ISSUE THREAD

**Issue by resistorsoftware** [zombocom/derailed_benchmarks#208]
I installed this gem to my development group, and I am trying to figure out why my production Rails 7 App is consuming so much memory. So I run this command, and whoa... what is up with dead_end? I get it, that is installed by this benchmark gem, in development, but why does it show up in profiling production? 

bundle exec derailed bundle:objects production
Measuring objects created by gems in groups [:default, "production"]
Total allocated: 48347847 bytes (432982 objects)
Total retained:  8143076 bytes (63574 objects)

allocated memory by gem
-----------------------------------
  36024877  dead_end-3.1.1
   2525440  ruby-3.1.1/lib

**Comment by tonywok** [comment]
Same issue here.

**Comment by schneems** [comment]
Close in favor of #204 lets move discussion there. Please see my response on that issue
