### ISSUE TITLE
breaking change in ruby-statistics v4: statistics -> ruby_statistics

### ISSUE THREAD

**Issue by espen** [zombocom/derailed_benchmarks#237]
https://github.com/estebanz01/ruby-statistics?tab=readme-ov-file#note-regarding-versions-3x-and-4x

> the gem got an update that introduced a breaking change in master where the Outermost namespace was changed to be ruby_statistics instead of statistics

Used here: https://github.com/zombocom/derailed_benchmarks/blob/b8489788371e250fa214d31eed43c877b0b876a4/lib/derailed_benchmarks/stats_from_dir.rb#L4

**Comment by pcai** [comment]
#239 #238 #241
