### ISSUE TITLE
Relax dependency on `get_process_mem`?

### ISSUE THREAD

**Issue by voikya** [zombocom/derailed_benchmarks#251]
`derailed_benchmarks` currently has a dependency on `get_process_mem ~> 0` . However, since July there has been a 1.0.0 version of `get_process_mem` that now cannot be loaded if `derailed_benchmarks` is installed.

Does `derailed_benchmarks` actually require the older version, or can this dependency be relaxed?

**Comment by schneems** [comment]
v2.2.1 is released. I got rid of the version requirement. We own it and it generally doesn't change it's API.
